name: Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy
      run: |
        ssh ubuntu@EC2_IP "
          cd election-commission-project &&
          git pull origin main &&
          pkill -f app.py &&
          nohup python3 app.py &
        "
